# Global Values
repoUrl: 'https://github.com/aws-samples/eks-blueprints-add-ons.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''

# Agones Values
agones: 
  enable: false 
  createNamespace: true

# App Mesh Values
appMesh: 
  enable: false 
  createNamespace: true

# Calico Values
calico:
  enable: false

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false
  createNamespace: true
  serviceAccountName:

# AWS EFS CSI Driver Values
awsEfsCsiDriver:
  enable: false
  serviceAccountName:

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  createNamespace: true
  logGroupName:
  serviceAccountName:

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: false
  createNamespace: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1

# AWS Node Termination Handler Values
awsNodeTerminationHandler:
  enable: false
  serviceAccountName:

# AWS Otel Collector Values
awsOtelCollector:
  enable: false
  createNamespace: true
  otlpEndpoint:
  resourceAttributes:

# Cert Manager Values
certManager:
  enable: false
  createNamespace: true
  serviceAccountName:

# Cert Manager CSI Driver Values
certManagerCsiDriver:
  enable: false

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:

# Datadog Operator
datadogOperator:
  enable: false

# Strimzi Kafka Operator
strimziKafkaOperator:
  enable: false

# External DNS Values
externalDns:
  enable: false
  createNamespace: true
  serviceAccountName:
  zoneIdFilter:

# External Secrets Operator
externalSecrets:
  enable: false

# Gatekeeper Values
gatekeeper:
  enable: false
  createNamespace: true
  clusterName:

# Nginx Values
ingressNginx:
  enable: false
  createNamespace: true

# Grafana default Values
grafana:
  enable: false
  serviceAccount:
    create: false

# Vault default Values
vault:
  enable: false

# Karpenter Values
karpenter:
  enable: false
  createNamespace: true
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:
  interruptionQueueName:

# Keda Values
keda:
  enable: false
  createNamespace: true
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: false

# Ondat Values
ondat:
  enable: false
  createNamespace: true
  etcdClusterCreate: false
  serviceAccountName:
  clusterSecretRefName:
  clusterAdminUsername:
  clusterAdminPassword:
  clusterKvBackendAddress:
  clusterKvBackendTLSSecretName:
  clusterKvBackendTLSSecretNamespace:
  clusterNodeSelectorTermKey:
  clusterNodeSelectorTermValue:
  etcdNodeSelectorTermKey:
  etcdNodeSelectorTermValue:
  etcdClusterReplicas:
  etcdClusterStorageclass:
  etcdClusterStorage:

# Prometheus Values
prometheus:
  enable: false
  createNamespace: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:

# Metrics Server Values
sparkOperator:
  enable: false
  createNamespace: true

# Tetrate Istio Values
tetrateIstio:
  enable: false
  createNamespace: true
  base:
  cni:
  istiod:
  global:

# Thanos Values
thanos:
  enable: false

# Traefik Values
traefik:
  enable: false
  createNamespace: true

# VPA Values
vpa:
  enable: false
  createNamespace: true

# Yunikorn Values
yunikorn:
  enable: false
  createNamespace: true

# Argo Rollout Values
argoRollouts:
  enable: false
  createNamespace: true

# Argo Rollout Values
argoWorkflows:
  enable: false

# Kube State Metrics Values
kubeStateMetrics:
  enable: false
  createNamespace: true
  serviceAccountName:

# Prometheus Node Exporter
promtheusNodeExporter:
  enable: false
  serviceAccountName:
  
# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: false
  serviceAccountName:

# promtail Values
promtail:
  enable: false

# kubecost Values
kubecost:
  enable: false

# SMB CSI Driver Values
smbCsiDriver:
  enable: false

# Chaos Mesh Values
chaosMesh:
  enable: false

# Cilium Mesh Values
cilium:
  enable: false

# Reloader Values
reloader:
  enable: false

# Kube Prometheus Stack
kubePrometheusStack:
  enable: false

# Kyverno Values
kyverno:
  enable: false

policies:
  enable: false

reporter:
  enable: false

# NVIDIA Device Plugin Values
nvidiaDevicePlugin:
  enable: false

# Consul Values
consul:
  enable: false
  
velero:
  enable: false

opentelemetryCollector:
  enable: false
  serviceAccountName:
