# Global Values
repo_url: "https://github.com/aws-samples/ssp-eks-add-ons.git"
region: ""
account: ""
clusterName: ""

# Agones Values
agones: 
  enable: false 

# App Mesh Values
appMesh: 
  enable: false 

# Calico Values
awsCalico:
  enable: false

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  logGroupName: 

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: false
  serviceAccountName:
  createIngressClassResource:

# AWS Otel Collector Values
awsOtelCollector:
  enable: false

# Cert Manager Values
certManager:
  enable: false
 
# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:

# External DNS Values
externalDns:
  enable: false
  zoneIdFilters: []

# Gatekeeper Values
gatekeeper: 
  enable: false

# Nginx Values
ingressNginx:
  enable: false

# Karpenter Values
karpenter: 
  enable: false
  serviceAccountName:
  controllerClusterName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:


# Keda Values
keda: 
  enable: false
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: false

# Prometheus Values
prometheus:
  enable: false
  serviceAccountName:
  roleArn: 
  ampWorkspaceUrl:

# Metrics Server Values
sparkOperator:
  enable: false

# Traefik Values
traefik:
  enable: false

# VPA Values
vpa: 
  enable: false
  serviceAccountName: 

# Yunikorn Values
yunikorn: 
  enable: false
  serviceAccountName: 
  operatorPlugins: 
  serviceType:
  embedAdmissionController:

# Argo Rollout Values
argoRollouts:
  enable: false
  serviceAccountName:

# Kube-state-metrics Values
kubeStateMetrics:
  enable: false
  serviceAccountName:
