karpenter:
  serviceAccount:
    create: false
    name: ""
  controller:
    clusterName: ""
    clusterEndpoint: ""
    nodeSelector:
      kubernetes.io/os: linux
  aws:
    defaultInstanceProfile: ""