{{- if and (.Values.agones) (.Values.agones.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repo_url }}
    path: add-ons/agones
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: agones-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.agones.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}