{{- if and (.Values.karpenter) (.Values.karpenter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/karpenter
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: karpenter.serviceAccount.name
          value: {{ .Values.karpenter.serviceAccountName }}
        - name: karpenter.clusterName
          value: {{ .Values.clusterName }}
        - name: karpenter.clusterEndpoint
          value: {{ .Values.karpenter.controllerClusterEndpoint }}
        - name: karpenter.aws.defaultInstanceProfile
          value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
