{{- if and (.Values.kubeStateMetrics) (.Values.kubeStateMetrics.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-add-ons
    path: add-ons/kube-state-metrics
    targetRevision: HEAD
    helm:
      parameters:
      - name: kube-state-metrics.serviceAccount.name
        value: {{ .Values.kubeStateMetrics.serviceAccountName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.kubeStateMetrics.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
