{{- if and (.Values.prometheus) (.Values.prometheus.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repo_url }}
    path: add-ons/prometheus
    targetRevision: HEAD
    helm:
      parameters:
      {{ if .Values.prometheus.serviceAccountName }}
      - name: prometheus.serviceAccounts.server.name
        value: {{ .Values.prometheus.serviceAccountName }}
      {{ end }}
      {{ if .Values.prometheus.roleArn }}
      - name: prometheus.serviceAccounts.server.annotations."eks\.amazonaws\.com/role-arn"
        value: {{ .Values.prometheus.roleArn }}
      {{ end }}
      {{ if .Values.prometheus.ampWorkspaceUrl }}
      - name: prometheus.server.remoteWrite[0].url
        value: {{ .Values.prometheus.ampWorkspaceUrl }}
      - name: prometheus.server.remoteWrite[0].sigV4.region
        value: {{ .Values.region }}
      {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.prometheus.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m 
{{- end -}}