{{- if and (.Values.yunikorn) (.Values.yunikorn.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yunikorn 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repo_url }}
    path: add-ons/yunikorn
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: yunikorn
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.yunikorn.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}