aws-for-fluent-bit:
  serviceAccount:
    create: false

  cloudWatch:
    enabled: true

  firehose:
    enabled: false

  kinesis:
    enabled: false

  elasticsearch:
    enabled: false

  tolerations:
    - operator: 'Exists'
